# Uncertainty score - output
## How to use:
1. Choose the image you want to check from a dataset and give to the function **image_to_tensor** as input the image index and dataset name. Save the output as your sample.
2. Run the function **output_certainty** with the model name and the sample name as inputs. It will return the certainty of the prediction on a scale *to be defined*.

In [222]:
# to suppress scientific notation (exponential)
torch.set_printoptions(sci_mode=False)

In [268]:
def image_to_tensor(image_index, dataset):
    image = [dataset[image_index][0]]
    # label optional, just to keep track
    label = [dataset[image_index][1]]
    # for final use, delete the 2nd object - the label (not present for "real" test image)
    return (torch.stack(image).float(), torch.tensor(label).long())

In [269]:
def prediction_scores(model, sample):
  # Setting the model to evaluation mode:
    model.eval()
    with torch.no_grad():
        x, y = sample
        x = x.to(device)
        prediction = model.forward(x)
        return prediction
# the output values add up to 1 (SoftMax?) --> can be interpreted as probablilities

In [270]:
# initialize a few samples for checkups
sample_a = image_to_tensor(5678, train_dataset) 
prediction_scores(model, sample_a)

tensor([[0.1983, 0.4137, 0.0866, 0.2948, 0.0032, 0.0035]])

In [271]:
sample_b = image_to_tensor(19, test_dataset) 
prediction_scores(model, sample_b)

tensor([[0.0018, 0.3911, 0.0024, 0.5998, 0.0026, 0.0023]])

In [274]:
sample_c = image_to_tensor(4567, test_dataset)
prediction_scores(model, sample_c)

tensor([[0.0598, 0.0014, 0.0494, 0.8865, 0.0015, 0.0014]])

In [275]:
sample_d = image_to_tensor(345, test_dataset)
prediction_scores(model, sample_d)

tensor([[    0.0078,     0.0009,     0.0016,     0.9880,     0.0010,     0.0007]])

In [280]:
# initial concept:
##  "high certainty" - "medium" - "low" - "very low"
##                  0.9        0.75     0.6
# literature research to support the choice needed

def output_certainty(model, sample):
    scores = prediction_scores(model, sample)
    print
    for i in scores.numpy()[0]:
        if i > 0.9:
            return "High certainty"
    for i in scores.numpy()[0]:
        if i > 0.75:
            return "Medium certainty"
    for i in scores.numpy()[0]:
        if i > 0.6:
            return "Low certainty"
    return "Very low certainty"

In [281]:
output_certainty(model, sample_a)

'Very low certainty'

In [282]:
output_certainty(model, sample_b)

'Very low certainty'

In [283]:
output_certainty(model, sample_c)

'Medium certainty'

In [284]:
output_certainty(model, sample_d)

'High certainty'